server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Trik SPA: Arahkan semua laluan yang tidak wujud kembali ke index.html
        try_files $uri $uri/ /index.html;
    }

    # Sembunyikan maklumat versi Nginx atas faktor keselamatan
    server_tokens off;
}